# -*- ruby -*-

# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake bundler:gemfile`.

source "https://rubygems.org/"

gem "dry-system", "~> 0.18"
gem "rom", "~> 5.2"
gem "rom-sql", "~> 3.3"
gem "ruby-oci8", "~> 2.2", require: 'oci8'
gem "dotenv", "~> 2.7"
gem "rake", "~> 13.0"
gem 'dry-auto_inject', "~> 0.7", require: 'dry/auto_inject'
gem 'dry-cli', "~> 0.6"
gem 'dry-view', "~> 0.7"
gem 'erbse', '~> 0.1'
gem 'dry-validation', "~> 1.6"
gem 'dry-matcher', "~> 0.9"
gem 'dry-monads', "~> 1.3"
gem "minitest", "~> 5.1", :group => [:development, :test]
gem "rdoc", ">=4.0", "<7", :group => [:development, :test]
gem "hoe", ">= 3.2", :group => [:development, :test]
gem 'tty-prompt', "~> 0.2"
gem 'pry', ">= 0.13"
gem 'pry-byebug', ">= 11"

# vim: syntax=ruby
