# -*- ruby -*-

# DO NOT EDIT THIS FILE. Instead, edit Rakefile, and run `rake bundler:gemfile`.

source "https://rubygems.org/"

gem "dry-system", "~>0.18"
gem "rom", "~>5.2"
gem "rom-sql", "~>3.3"
gem "ruby-oci8", ">=2.2"
gem "dry-auto_inject", "~>0.7"
gem "dry-view", "~>0.7"
gem "dry-cli", "~>0.6"
gem "dotenv", "~>2.7"
gem "rake", "~>13.0"

gem "minitest", "~>5.14", :group => [:development, :test]
gem "rdoc", ">=4.0", "<7", :group => [:development, :test]
gem "hoe", "~>3.22", :group => [:development, :test]

# vim: syntax=ruby
